from pydantic import BaseModel, Field
from typing import List, Optional
from app.schemas.knowledge_schemas import Citation

class ChatMessage(BaseModel):
    role: str = Field(..., description="Either 'user', 'assistant', or 'system'")
    content: str = Field(..., description="The context message text copy")

class InteractivePRDRequest(BaseModel):
    workspace_id: str
    product_name: str
    messages: List[ChatMessage] = Field(..., description="The full conversation history stream stack")
    target_audience: Optional[str] = "Enterprise Teams"
    tech_stack_focus: Optional[str] = "FastAPI, MongoDB, React"
    document_id: Optional[str] = Field(None, description="Passed once the anchor document is spawned")
    project_id: Optional[str] = Field(None, description="Passed to associate generated plans with projects")
    mode: Optional[str] = "chat"
    current_feature: Optional[int] = Field(1, description="Deterministic pointer for the sequential 22-feature walkthrough")

class InteractivePRDResponse(BaseModel):
    job_id: str = Field(..., description="The unique UUID token assigned to this background calculation task")
    document_id: str = Field(..., description="The document unique tracking identity string mapping the single active file")
    status: str = Field("processing", description="Initial lifecycle state tracking metric")

class JobStatusResponse(BaseModel):
    job_id: str = Field(..., description="The targeting UUID verification token")
    status: str = Field(..., description="Current computation phase state: 'processing', 'completed', or 'failed'")
    response: Optional[str] = Field(None, description="The complete text or Markdown reply generated by LM Studio once completed")
    change_summary: Optional[str] = Field(None, description="The isolated, high-level structural change summary description")
    is_complete: bool = Field(False, description="Evaluates to true once the final PRD blueprint pass finishes compilation")
    citations: Optional[List[Citation]] = Field(default_factory=list, description="Knowledge base sources grounded into the answer")